apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    name: postgresql-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgresql
      image: postgresql:9.4
      ports:
        - containerPort: 5432