apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-pod
    app: demo-voting-app
spec:
  selector:
    name: postgresql-pod
    app: demo-voting-app
  ports:
    - port: 5432
      targetPort: 5432
