apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
  labels:
    name: resultapp-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    name: resultapp-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
