apiVersion: v1
kind: Service
metadata:
  name: votingapp-service
  labels:
    name: votingapp-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    name: votingapp-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
